### ISSUE TITLE
2 errors

### ISSUE THREAD

**Issue by ghost** [thatsailorman/cryptoportfolio#2]
Hi,

1) index.php forwards to login.html (should be login.php as login.html does not exist)
2) login.php page comes up blank

Please fix so I can install and use,

Thanks

**Comment by ghost** [comment]
I might be able to fix it myself if I can figure out GitHub :)

Gimme a bit to figure it out but I have the fix for you :D

**Comment by thatsailorman** [comment]
Github blocks .htaccess files so it seems...

It's an easy fix.

1 - create a file .htaccess (yes, including the dot at the beginning)

2 - Add the following lines to the .htaccess file:

RewriteEngine on

RewriteRule ^(.*).html$ $1.php [L]



Good luck! Should be working now (my bad, didn't know Github doesn't let me upload .htaccess files). I've also added the info to the readme.

**Comment by ghost** [comment]
Sorry buddy I already forked it, decided it was not worth the time to code
it the way I wanted and moved on ...

Thanks anyways
